apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
  - name: python-container
    image: python:3.9
    command: ["sleep", "3600"]
