apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: demo-secret
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
