apiVersion: v1
kind: Pod
metadata:
  name: nginx-multi-container-pod
  labels:
    app: nginx-multi
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 81
    - name: sidecar
      image: busybox:latest
      command: ["sh", "-c", "while true; do echo 'Sidecar container is running'; sleep 10; done"]
